### ISSUE TITLE
GetInsights "page_fans_country" even if you are NOT the owner of the page

### ISSUE THREAD

**Issue by dengelha** [pablobarbera/Rfacebook#59]
Hey guys, all my respect to pablobarbera for this great Rfacebook package !!!

Since today, I get the following error after requesting:

> pagefansbycountry <- getInsights(object_id=FBPAGENAME, tok .... [TRUNCATED] 

> Error in getInsights(object_id = FBPAGENAME, token = fb_oauth, metric = "page_fans_country",  : No data available. Are you the owner of this page? See ?getInsights.

Before, it was possible to get the page_fans_country, even if you're not the owner of the page.

Could you please bring this function back? It was very useful!
It would be a pleasure helping you testing! 

All the best, 
David

**Comment by andrewgeisler** [comment]
@dengelha Thanks for reporting this. This has to do with the version of the API the function is using (v2.5). I did some reason using the API explorer too and it looks like the latest version to allow what you're doing is 2.3.  I like that the API is using that latest version because it will provide a better error response method. However, I see no reason I add the ability to specify a different version. I'll work on that. Thanks.

**Comment by andrewgeisler** [comment]
I've made edits and submitted a pull request. Once merged, I'll close this out.

**Comment by andrewgeisler** [comment]
@dengelha It got merged in earlier today. Thanks!

**Comment by dengelha** [comment]
Hey Pablo and Andrew, 
thank you soooo much for your efforts !!!

Nevertheless, the new "version" parameter in GetInsights is not working concerning #59.

Unfortunately, the "page_fans_by_country" (for everyone who is NOT THE OWNER OF THIS PAGE) is still not fixed.
Prior you guys implemented changes on either #52 or #58 (last weeks in Feb 2016), it was possible to retrieve page_fans_by_country via GetInsights, even if you are NOT THE OWNER.

This function was so useful. Can you please bring it back? Maybe, you can make it a seperate external function, outside "GetInsights" if it conflicts with newer fixes like the multiple stuff.

Let me know, if I can help! And thanks again, you guys rock !!

**Comment by andrewgeisler** [comment]
Sorry it's not working for you. It definitely worked for me at the time of the fix. 

Can you share the following?
- The code you're using for the function?
- The error. Is it the same?
- Are you able to get this info via the API explorer tool at all?

**Comment by dengelha** [comment]
Directly in the Graph API Explorer, it works with "?fields=insights{values}" for v2.0 - v2.3 !

But in R, typing:
> getInsights(object_id="BLABLABLA", token=fb_oauth, metric='page_fans_country', period='lifetime', version = 2.3)

I get:
```
Error in FUN(X[[i]], ...) : 
  No data available. Are you the owner of this page? See ?getInsights.
```

Thx!

**Comment by andrewgeisler** [comment]
@dengelha 

I'm unable to recreate this issue. I've successfully retrieved this metric for 5 or 6 different FB pages I'm not associated with at all. 

Sorry this is silly to ask but I must, you did pull down the most recent master from github, correct?

**Comment by pablobarbera** [comment]
The following works for me as well:
```
getInsights(object_id="humansofnewyork", token=token, metric='page_fans_country', 
period='lifetime', version = 2.3)
```
And I just released to CRAN the most recent version of the package, so this should work with both the GitHub and CRAN versions of the package.
(And kind of cool that this information is available! I had no idea)

**Comment by dengelha** [comment]
@andrewgeisler 

Thank you! That wasn't a silly question. I just re-installed Rfacebook via CRAN, as I am not quite able to "pull down the master from GitHub".

But Pablo confirmed, it might be also working via CRAN.

I guess, I might have limitations in my fb_oauth, although every other features are still working great.
But still, when I query for:

`getInsights(object_id="humansofnewyork", token=fb_oauth, metric='page_fans_country',period='lifetime', version = 2.3)`

I get: 

> Error in FUN(X[[i]], ...) : 
  No data available. Are you the owner of this page? See ?getInsights.

Any other idea?

**Comment by pablobarbera** [comment]
Can you share the output of your sessionInfo() ?
You can reinstall from Github with the following code:
```
library(devtools)
install_github("pablobarbera/Rfacebook/Rfacebook")
```

**Comment by dengelha** [comment]
```
R version 3.2.3 (2015-12-10)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.3 httpuv_1.3.3    rjson_0.2.15    httr_1.1.0     
[5] devtools_1.10.0

loaded via a namespace (and not attached):
[1] R6_2.1.2      curl_0.9.6    Rcpp_0.12.3   memoise_1.0.0 git2r_0.13.1 
[6] digest_0.6.9 

```
I removed the info on location and OS. 
Thanx for the reinstall-instructions, still not working via git.

**Comment by andrewgeisler** [comment]
@dengelha I ran the following:

> getInsights(object_id="humansofnewyork", token=token, metric='page_fans_country',period='lifetime', version = 2.3)

> getInsights(object_id="humansofnewyork", token=tokenApiExplore, metric='page_fans_country',period='lifetime', version = 2.3)

The only difference being the token used. I inserted the token I always use for FB requests. I also went and got a different token from the API explorer (just used the one that automatically showed up.. I changed nothing). 

Both tests came back with results. `

**Comment by dengelha** [comment]
Wonderful !!! I am sooo happy, IT IS BACK !!!!!
Thanks @andrewgeisler and @pablobarbera for your valuable time and effort.
Rfacebook rocks! 

Greetings from Germany,
David
